import { useTranslation } from "react-i18next";

import { Figure } from "@/components/Figure";
import { Equation } from "@/components/Equation";
import { PageShell } from "@/components/PageShell";
import { Section } from "@/components/Section";

export default function MethodologyTheory() {
  const { t } = useTranslation(["pages"]);
  return (
    <PageShell
      title={t("pages:methodology_theory.title")}
      lead="Probabilistic topic models over hyperspectral imagery — what they are, how they work, and why a pixel can be treated as a document."
    >
      <Section
        id="why-ptm"
        title="What is a probabilistic topic model?"
        lead="A probabilistic topic model (PTM) describes every document as a latent mixture over a handful of word distributions called topics. The key point is that this latent structure is learned without supervision from word co-occurrences alone."
      >
        <p>
          Under the most popular model — Latent Dirichlet Allocation (Blei, Ng &amp;
          Jordan, 2003) — a corpus of <em>D</em> documents over a vocabulary of
          size <em>V</em> is explained by two families of distributions:{" "}
          <Equation tex="\theta_d \in \Delta^{K-1}" /> is the topic mixture of
          document <em>d</em>, and <Equation tex="\phi_k \in \Delta^{V-1}" /> is
          the word distribution of topic <em>k</em>. Every observed word is
          generated by first drawing a topic from <Equation tex="\theta_d" /> and
          then a word from the corresponding <Equation tex="\phi_k" />.
        </p>
        <p className="mt-3">
          Inference recovers <Equation tex="\theta" />, <Equation tex="\phi" /> and
          the topic-per-word assignment <Equation tex="z" />. The result is a
          compact, interpretable, mixed decomposition of the corpus: every
          document is a mixture of topics instead of belonging to a single hard
          class.
        </p>
      </Section>

      <Section
        id="lda-plate"
        title="LDA — plate notation and generative process"
        lead="The outer plates repeat over documents and words; the latent distributions (theta and phi) are the objects the model learns."
      >
        <Figure caption="LDA in plate notation. The outer plate iterates over the D documents; the inner plate, over the N_d words of each document. Theta_d is the per-document mixture over K topics; phi_k is the distribution of topic k over the V vocabulary words.">
          <PlateNotationSVG />
        </Figure>

        <p>
          The joint distribution of the model factorises as follows (with
          Dirichlet priors on <Equation tex="\theta_d" /> and <Equation tex="\phi_k" />):
        </p>

        <Equation
          block
          tex="p(\theta, \phi, z, w \mid \alpha, \eta) = \prod_{k=1}^{K} p(\phi_k \mid \eta) \, \prod_{d=1}^{D} p(\theta_d \mid \alpha) \prod_{n=1}^{N_d} p(z_{d,n} \mid \theta_d) \, p(w_{d,n} \mid z_{d,n}, \phi_{1:K})"
        />

        <p>
          The corpus marginal likelihood is obtained by integrating the
          continuous latents and summing over the discrete assignments:
        </p>
        <Equation
          block
          tex="p(w \mid \alpha, \eta) = \int \int \, \prod_{k} p(\phi_k \mid \eta) \, \prod_{d} p(\theta_d \mid \alpha) \prod_{n} \sum_{k=1}^{K} \theta_{d,k} \, \phi_{k, w_{d,n}} \, d\theta \, d\phi"
        />
        <p>
          That integral is intractable in closed form. Inference proceeds via
          variational Bayes (Blei et al. 2003), collapsed Gibbs (Griffiths &amp;
          Steyvers 2004) or stochastic VI (Hoffman et al. 2013); all of them are
          approximations to the same posterior.
        </p>
      </Section>

      <Section
        id="hsi-as-document"
        title="HSI as a corpus — why a pixel can be a document"
        lead="Each pixel of a hyperspectral image is a reflectance vector. For LDA to consume it, the spectrum must be quantised and turned into a discrete sequence of tokens."
      >
        <p>
          A hyperspectral image (HSI) is a cube{" "}
          <Equation tex="X \in \mathbb{R}^{H \times W \times B}" />, where each
          pixel <Equation tex="(i, j)" /> has a spectrum{" "}
          <Equation tex="x_{ij} = (x_{ij,1}, \dots, x_{ij,B})" /> with the
          reflectance observed in each of the <em>B</em> spectral bands. Typical
          band counts: 200 (Indian Pines AVIRIS-Classic) to 224 (Salinas) to
          more than 2000 (HIDSAG).
        </p>
        <p className="mt-3">
          The spectrum → document conversion is called{" "}
          <strong>wordification</strong>. A wordification recipe declares
          (i) how the spectrum is normalised, (ii) how intensities are
          quantised, (iii) what counts as a token (band, intensity, derivative,
          wavelet coefficient, VQ code, etc.) and (iv) what counts as a document
          (a pixel, a SLIC region, a patch, a full sample). The result is a
          document-term matrix{" "}
          <Equation tex="C \in \mathbb{N}^{D \times V}" /> over which LDA can
          infer.
        </p>

        <Figure caption="Wordification pipeline: continuous spectrum → normalisation → Q-level quantisation → token emission → document. The alphabet and token recipe are chosen to preserve the property of interest (band, shape, absorption, endmember abundance, VQ code).">
          <WordificationFlowSVG />
        </Figure>

        <p>
          The project ships twelve recipes (V1 wavelength-as-word to V12 GMM
          token), three quantisation schemes (uniform, quantile, Lloyd-Max) and
          three levels <em>Q</em> ∈ {`{8, 16, 32}`}. Each combination produces a
          distinct corpus and therefore a distinct LDA solution.
        </p>
      </Section>

      <Section
        id="why-mixed-membership"
        title="Mixed membership — why not hard classification?"
        lead="The spectrum of a mineral pixel does not come from a single species. Mixtures, intermixed vegetation, shadow and atmospheric scattering yield measurements that reflect several signatures at once."
      >
        <p>
          The hard-membership assumption — a pixel belongs to exactly one
          class — fails in HSI because every spectrum is by construction a
          mixture. LDA's mixed decomposition captures that reality directly:{" "}
          <Equation tex="\theta_d" /> is the topical composition of pixel{" "}
          <em>d</em>, and the sum <Equation tex="\sum_{k} \theta_{d,k} \phi_k" /> is
          the reconstructed signature that the model believes generated the
          observed words.
        </p>
        <p className="mt-3">
          Compare against a linear baseline (PCA, NMF, ICA) on the same cube:
          those methods also produce a low-dimensional representation, but
          without a generative model of discrete counts and, crucially, without
          the interpretability of "topic = distribution over spectral words".
          The Application page goes deeper on when each is preferable.
        </p>

        <Figure caption="Mixed membership: each pixel of the hyperspectral map is decomposed into a θ_d proportion over the K topics. The weighted sum of topic signatures reconstructs a smoothed version of the original spectrum.">
          <MixedMembershipSVG />
        </Figure>
      </Section>

      <Section id="readings" title="Minimal reading list">
        <ul
          className="mt-2 space-y-2 list-disc pl-5"
          style={{ color: "var(--color-fg-subtle)" }}
        >
          <li>
            Blei, Ng &amp; Jordan (2003) — <em>Latent Dirichlet Allocation</em>.
            JMLR. The canonical paper.
          </li>
          <li>
            Griffiths &amp; Steyvers (2004) —{" "}
            <em>Finding scientific topics</em>. PNAS. Collapsed Gibbs.
          </li>
          <li>
            Sievert &amp; Shirley (2014) —{" "}
            <em>LDAvis: A method for visualizing and interpreting topics</em>.
            Defines the relevance formula λ used in the Workspace page.
          </li>
          <li>
            Stammbach et al. (2024) — <em>Re-visiting word intrusion</em>. TACL.
            Modern framework for validating topics with LLM oracles.
          </li>
        </ul>
      </Section>
    </PageShell>
  );
}

function PlateNotationSVG() {
  return (
    <svg
      width="560"
      height="260"
      viewBox="0 0 560 260"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-label="LDA plate notation"
      style={{ color: "var(--color-fg)" }}
    >
      <defs>
        <marker
          id="arrowTheory"
          viewBox="0 0 10 10"
          refX="8"
          refY="5"
          markerWidth="6"
          markerHeight="6"
          orient="auto-start-reverse"
        >
          <path d="M0 0 L10 5 L0 10 z" fill="currentColor" />
        </marker>
      </defs>
      <g
        fill="none"
        stroke="currentColor"
        strokeWidth="1.4"
        fontFamily="ui-sans-serif, system-ui, sans-serif"
        fontSize="13"
      >
        <rect x="20" y="40" width="380" height="190" rx="8" />
        <text x="380" y="220" fill="currentColor" textAnchor="end">
          D
        </text>
        <rect x="100" y="100" width="280" height="110" rx="8" />
        <text x="360" y="200" fill="currentColor" textAnchor="end">
          N_d
        </text>
        <rect x="430" y="40" width="110" height="80" rx="8" />
        <text x="525" y="110" fill="currentColor" textAnchor="end">
          K
        </text>

        <circle cx="40" cy="70" r="14" fill="var(--color-bg)" />
        <text x="40" y="74" textAnchor="middle" fill="currentColor">
          α
        </text>
        <circle cx="450" cy="70" r="14" fill="var(--color-bg)" />
        <text x="450" y="74" textAnchor="middle" fill="currentColor">
          η
        </text>

        <circle cx="80" cy="140" r="18" fill="var(--color-accent-soft)" />
        <text x="80" y="144" textAnchor="middle" fill="currentColor">
          θ_d
        </text>

        <circle cx="190" cy="155" r="18" fill="var(--color-accent-soft)" />
        <text x="190" y="159" textAnchor="middle" fill="currentColor">
          z
        </text>

        <circle cx="300" cy="155" r="18" fill="var(--color-accent)" />
        <text x="300" y="159" textAnchor="middle" fill="var(--color-accent-fg)">
          w
        </text>

        <circle cx="490" cy="80" r="18" fill="var(--color-accent-soft)" />
        <text x="490" y="84" textAnchor="middle" fill="currentColor">
          φ_k
        </text>

        <line x1="56" y1="70" x2="62" y2="125" markerEnd="url(#arrowTheory)" />
        <line
          x1="100"
          y1="145"
          x2="170"
          y2="153"
          markerEnd="url(#arrowTheory)"
        />
        <line
          x1="210"
          y1="155"
          x2="280"
          y2="155"
          markerEnd="url(#arrowTheory)"
        />
        <line
          x1="478"
          y1="92"
          x2="320"
          y2="148"
          markerEnd="url(#arrowTheory)"
        />
        <line
          x1="450"
          y1="84"
          x2="475"
          y2="73"
          markerEnd="url(#arrowTheory)"
        />
      </g>
    </svg>
  );
}

function WordificationFlowSVG() {
  return (
    <svg
      width="640"
      height="220"
      viewBox="0 0 640 220"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-label="Wordification pipeline"
      style={{ color: "var(--color-fg)" }}
    >
      <defs>
        <marker
          id="arrowWord"
          viewBox="0 0 10 10"
          refX="8"
          refY="5"
          markerWidth="6"
          markerHeight="6"
          orient="auto-start-reverse"
        >
          <path d="M0 0 L10 5 L0 10 z" fill="currentColor" />
        </marker>
      </defs>
      <g
        fontFamily="ui-sans-serif, system-ui, sans-serif"
        fontSize="12"
        fill="currentColor"
      >
        <rect
          x="20"
          y="60"
          width="120"
          height="100"
          rx="8"
          fill="var(--color-panel)"
          stroke="currentColor"
          strokeWidth="1.3"
        />
        <text x="80" y="80" textAnchor="middle" fontWeight="600">
          Espectro
        </text>
        <path
          d="M 30 130 C 50 100, 70 160, 90 110 S 130 90, 130 130"
          fill="none"
          stroke="var(--color-accent)"
          strokeWidth="1.6"
        />
        <text x="80" y="155" textAnchor="middle" opacity="0.7">
          x ∈ ℝ^B
        </text>

        <rect
          x="170"
          y="60"
          width="120"
          height="100"
          rx="8"
          fill="var(--color-panel)"
          stroke="currentColor"
          strokeWidth="1.3"
        />
        <text x="230" y="80" textAnchor="middle" fontWeight="600">
          Normalización
        </text>
        <text x="230" y="115" textAnchor="middle" opacity="0.85">
          per-spectrum,
        </text>
        <text x="230" y="132" textAnchor="middle" opacity="0.85">
          per-band o
        </text>
        <text x="230" y="149" textAnchor="middle" opacity="0.85">
          reflectancia
        </text>

        <rect
          x="320"
          y="60"
          width="120"
          height="100"
          rx="8"
          fill="var(--color-panel)"
          stroke="currentColor"
          strokeWidth="1.3"
        />
        <text x="380" y="80" textAnchor="middle" fontWeight="600">
          Cuantización
        </text>
        <g stroke="var(--color-accent)" strokeWidth="1.6" fill="none">
          <line x1="335" y1="100" x2="425" y2="100" />
          <line x1="335" y1="115" x2="425" y2="115" />
          <line x1="335" y1="130" x2="425" y2="130" />
          <line x1="335" y1="145" x2="425" y2="145" />
        </g>
        <text x="380" y="158" textAnchor="middle" opacity="0.7">
          uniform / quantile / Lloyd-Max
        </text>

        <rect
          x="470"
          y="60"
          width="150"
          height="100"
          rx="8"
          fill="var(--color-panel)"
          stroke="currentColor"
          strokeWidth="1.3"
        />
        <text x="545" y="80" textAnchor="middle" fontWeight="600">
          Tokens
        </text>
        <text x="545" y="105" textAnchor="middle" opacity="0.85">
          V1, V2, … V12
        </text>
        <text x="545" y="125" textAnchor="middle" opacity="0.7">
          (band, q) | (k, α_k)
        </text>
        <text x="545" y="143" textAnchor="middle" opacity="0.7">
          (centroid, depth, area)
        </text>

        <g
          stroke="currentColor"
          strokeWidth="1.4"
          fill="none"
          markerEnd="url(#arrowWord)"
        >
          <line x1="142" y1="110" x2="166" y2="110" />
          <line x1="292" y1="110" x2="316" y2="110" />
          <line x1="442" y1="110" x2="466" y2="110" />
        </g>
      </g>
    </svg>
  );
}

function MixedMembershipSVG() {
  return (
    <svg
      width="560"
      height="240"
      viewBox="0 0 560 240"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-label="Mixed-membership reconstruction"
      style={{ color: "var(--color-fg)" }}
    >
      <defs>
        <linearGradient id="gradT1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#0ea5e9" stopOpacity="0.8" />
          <stop offset="100%" stopColor="#0ea5e9" stopOpacity="0.1" />
        </linearGradient>
        <linearGradient id="gradT2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#f97316" stopOpacity="0.8" />
          <stop offset="100%" stopColor="#f97316" stopOpacity="0.1" />
        </linearGradient>
        <linearGradient id="gradT3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#22c55e" stopOpacity="0.8" />
          <stop offset="100%" stopColor="#22c55e" stopOpacity="0.1" />
        </linearGradient>
      </defs>
      <g
        fontFamily="ui-sans-serif, system-ui, sans-serif"
        fontSize="12"
        fill="currentColor"
      >
        <rect
          x="20"
          y="80"
          width="80"
          height="80"
          fill="var(--color-accent)"
          opacity="0.85"
        />
        <text x="60" y="180" textAnchor="middle" fontWeight="600">
          píxel d
        </text>

        <text x="160" y="62" fontWeight="600">
          θ_d (mezcla)
        </text>
        <g>
          <rect x="160" y="80" width="200" height="20" fill="#0ea5e9" />
          <rect x="360" y="80" width="120" height="20" fill="#f97316" />
          <rect x="480" y="80" width="50" height="20" fill="#22c55e" />
          <text x="260" y="95" textAnchor="middle" fill="#fff" fontSize="11">
            tópico 1 — 0.59
          </text>
          <text x="420" y="95" textAnchor="middle" fill="#fff" fontSize="11">
            tópico 2 — 0.27
          </text>
          <text x="505" y="95" textAnchor="middle" fill="#fff" fontSize="11">
            t3
          </text>
        </g>

        <text x="160" y="130" fontWeight="600">
          φ_k (firmas tópicas)
        </text>
        <g transform="translate(160, 140)">
          <path
            d="M 0 60 C 30 40, 60 70, 90 30 S 150 50, 200 35"
            stroke="#0ea5e9"
            strokeWidth="1.8"
            fill="url(#gradT1)"
          />
        </g>
        <g transform="translate(160, 165)">
          <path
            d="M 0 50 C 30 30, 70 60, 110 25 S 170 50, 200 45"
            stroke="#f97316"
            strokeWidth="1.8"
            fill="url(#gradT2)"
          />
        </g>
        <g transform="translate(160, 190)">
          <path
            d="M 0 40 C 40 25, 80 45, 120 15 S 180 30, 200 28"
            stroke="#22c55e"
            strokeWidth="1.8"
            fill="url(#gradT3)"
          />
        </g>

        <text x="400" y="130" fontWeight="600">
          Reconstrucción
        </text>
        <text x="400" y="148" opacity="0.85">
          Σ θ_dk · φ_k
        </text>
        <g transform="translate(400, 160)">
          <path
            d="M 0 50 C 25 25, 60 65, 95 20 S 145 40, 150 35"
            stroke="currentColor"
            strokeWidth="1.8"
            fill="none"
          />
        </g>
      </g>
    </svg>
  );
}
